### ISSUE TITLE
Write access

### ISSUE THREAD

**Issue by heff** [muxinc/dash-video-element#2]
@wilaw at some point I lost write access to this repo, can I get it again? I need to upgrade the element.

Or if it's complicated to give me write access now, I can always move the repo elsewhere.

Thanks!

**Comment by wilaw** [comment]
Sorry about that. It seems there was a clean-out and someone removed admins not regularly involved in DASH IF. I have re-added you with admin permissions. Can you confirm it's all good?

**Comment by heff** [comment]
No worries! In #1 for me it still says "Only those with write access to this repository can merge pull requests." So I don't think it worked. I tried re logging in and no change.

**Comment by heff** [comment]
Found the issue. Core team only has Read access for this repo.
![image](https://user-images.githubusercontent.com/166/125122954-eff7f900-e0aa-11eb-9469-c4083de17c49.png)

**Comment by wilaw** [comment]
Core now has admin access for dash-video-element. Can you retry?

![image](https://user-images.githubusercontent.com/2762250/125123841-0eaabf80-e0ac-11eb-8794-e2455d30beca.png)

**Comment by heff** [comment]
Awesome, confirmed. Thank you!
